import { Nunito } from 'next/font/google'
import './globals.css'

const font = Nunito({ subsets: ['latin'] })

export const metadata = {
  icons: {
    icon: {url:'img/favicon.png', type: 'image/png'}
  },
  title: 'Mockup ADN',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type='image/icon' href='/img/favicon.png' />
      </head>
      <body className={font.className}>{children}
      </body>
    </html>
  )
}
